packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^4.12.0
    '@antfu/ni': ^24.3.0
    '@modelcontextprotocol/inspector': ^0.8.2
    bumpp: ^10.1.0
    eslint: ^9.24.0
    lint-staged: ^15.5.1
    nodemon: ^3.1.9
    simple-git-hooks: ^2.12.1
    tsx: ^4.19.3
    typescript: ~5.8.3
    unbuild: ^3.5.0
    vite: ^6.2.6
    vue-tsc: ^2.2.8
  nuxt:
    '@nuxt/devtools': ^2.3.2
    '@nuxt/eslint-config': ^1.3.0
    '@nuxt/kit': ^3.16.2
    '@nuxt/module-builder': ^1.0.1
    '@nuxt/schema': ^3.16.2
    '@nuxt/test-utils': ^3.17.2
    nitropack: ^2.11.9
    nuxi: ^3.24.1
    nuxt: ^3.16.2
  prod:
    '@modelcontextprotocol/sdk': ^1.9.0
    ansis: ^3.17.0
    async-cache-dedupe: ^2.2.0
    citty: ^0.1.6
    debug: ^4.4.0
    h3: ^1.15.1
    pathe: ^2.0.3
    unimport: ^5.0.0
    zod: ^3.24.2
  testing:
    vitest: ^3.1.1
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.1
  types:
    '@types/debug': ^4.1.12
    '@types/node': latest
  utils:
    '@antfu/utils': ^9.2.0
    tinyexec: ^1.0.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
